order:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: order_online
    username: root
    password: 123456
  local-storage:
    location: D:/tmp/order
    base-url: http://localhost:8080/file
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
